import { mkdir, writeFile } from 'node:fs/promises'
import { chromium, type Page } from 'playwright'

const BASE_URL = 'https://pixijs.io/ui/'
const OUTPUT_DIR = new URL('../docs/pixi-ui/', import.meta.url)

type DocLink = {
  text: string
  url: string
}

const CONTENT_SELECTORS = ['main article', 'article', '.content', 'main']

async function waitForDocPage(page: Page): Promise<void> {
  await page.waitForLoadState('domcontentloaded')
  await page.waitForFunction(function () {
    const body = document.body

    if (!body) {
      return false
    }

    const heading = document.querySelector('h1, h2, article h1, article h2')
    const contentHost = document.querySelector('article, .content, .container, .main, .page, body')

    return Boolean(heading && contentHost && contentHost.textContent?.trim())
  })
}

function toSlug(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function normalizeMarkdown(markdown: string): string {
  return markdown
    .replace(/[\uE000-\uF8FF]/g, '')
    .replace(/[ \t]+\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .replace(/^\s*[-*]\s*$/gm, '')
    .replace(/^\s*Documentation generated by .*$/gim, '')
    .replace(/\n(?:\s*inherited\s*\n){2,}/g, '\n\ninherited\n')
    .trim()
}

function createDocumentMarkdown(title: string, sourceUrl: string, content: string): string {
  return [`# ${title}`, '', `Source: ${sourceUrl}`, '', content]
    .filter(Boolean)
    .join('\n')
}

async function collectDocLinks(page: Page): Promise<DocLink[]> {
  return page.evaluate(function (baseUrl: string) {
    const seen = new Set<string>()
    const baseOrigin = new URL(baseUrl).origin
    const anchors = Array.from(document.querySelectorAll('aside a[href], nav a[href], a[href]')) as HTMLAnchorElement[]
    const items: DocLink[] = []

    for (const anchor of anchors) {
      const text = anchor.textContent?.trim() ?? ''
      const href = anchor.getAttribute('href') ?? ''

      if (!text || !href || /github/i.test(text)) {
        continue
      }

      const url = new URL(href, baseUrl)

      if (url.origin !== baseOrigin || !url.pathname.startsWith('/ui')) {
        continue
      }

      const isIndexPage = url.pathname === '/ui/' || url.pathname === '/ui/index.html'
      const isHtmlDoc = url.pathname.endsWith('.html')

      if (!isIndexPage && !isHtmlDoc) {
        continue
      }

      url.hash = ''
      const normalizedUrl = url.toString()

      if (seen.has(normalizedUrl)) {
        continue
      }

      seen.add(normalizedUrl)
      items.push({ text, url: normalizedUrl })
    }

    return items
  }, BASE_URL)
}

async function extractMarkdown(page: Page): Promise<string> {
  for (const selector of CONTENT_SELECTORS) {
    const locator = page.locator(selector).first()

    if ((await locator.count()) === 0) {
      continue
    }

    const markdown = normalizeMarkdown(
      await locator.evaluate(function (element) {
        const root = element as HTMLElement
        const removableSelectors = [
          'nav',
          'aside',
          'header',
          'footer',
          'script',
          'style',
          'svg',
          'img',
          '.menu',
          '.sidebar',
          '.toc',
          '.navigation',
          '.page-toc'
        ]
        const clone = root.cloneNode(true) as HTMLElement
        const blocks: string[] = []
        const nodes = clone.querySelectorAll(removableSelectors.join(', '))

        for (const node of nodes) {
          node.remove()
        }

        const candidates = clone.querySelectorAll('h1, h2, h3, h4, h5, h6, pre, table, ul, ol, blockquote, dl, p')

        for (const candidate of candidates) {
          if (!(candidate instanceof HTMLElement)) {
            continue
          }

          const parentBlock = candidate.parentElement?.closest('pre, table, ul, ol, blockquote, dl')

          if (parentBlock && parentBlock !== candidate) {
            continue
          }

          const tag = candidate.tagName

          if (tag === 'PRE') {
            const code = candidate.textContent?.replace(/^\n+|\n+$/g, '') ?? ''

            if (code) {
              blocks.push(`\`\`\`ts\n${code}\n\`\`\``)
            }

            continue
          }

          if (tag === 'TABLE') {
            const rows = candidate.querySelectorAll('tr')
            const tableLines: string[] = []
            let headerLength = 0

            for (const row of rows) {
              const cells = row.querySelectorAll('th, td')
              const values: string[] = []

              for (const cell of cells) {
                const text = (cell.textContent ?? '').replace(/[\uE000-\uF8FF]/g, '').replace(/\s+/g, ' ').trim()

                if (text) {
                  values.push(text)
                }
              }

              if (values.length === 0) {
                continue
              }

              if (headerLength === 0) {
                headerLength = values.length
                tableLines.push(`| ${values.join(' | ')} |`)
                tableLines.push(`| ${new Array(values.length).fill('---').join(' | ')} |`)
              } else {
                while (values.length < headerLength) {
                  values.push('')
                }

                tableLines.push(`| ${values.join(' | ')} |`)
              }
            }

            if (tableLines.length > 0) {
              blocks.push(tableLines.join('\n'))
            }

            continue
          }

          if (tag === 'UL' || tag === 'OL') {
            const items = candidate.querySelectorAll(':scope > li')
            const listLines: string[] = []
            let index = 1

            for (const item of items) {
              const text = (item.textContent ?? '').replace(/[\uE000-\uF8FF]/g, '').replace(/\s+/g, ' ').trim()

              if (!text) {
                continue
              }

              if (tag === 'OL') {
                listLines.push(`${index}. ${text}`)
                index += 1
              } else {
                listLines.push(`- ${text}`)
              }
            }

            if (listLines.length > 0) {
              blocks.push(listLines.join('\n'))
            }

            continue
          }

          if (tag === 'DL') {
            const parts: string[] = []
            let currentTitle = ''

            for (const child of candidate.children) {
              const text = (child.textContent ?? '').replace(/[\uE000-\uF8FF]/g, '').replace(/\s+/g, ' ').trim()

              if (!text) {
                continue
              }

              if (child.tagName === 'DT') {
                currentTitle = text
                continue
              }

              if (child.tagName === 'DD') {
                parts.push(currentTitle ? `- ${currentTitle}: ${text}` : `- ${text}`)
              }
            }

            if (parts.length > 0) {
              blocks.push(parts.join('\n'))
            }

            continue
          }

          if (tag === 'BLOCKQUOTE') {
            const text = (candidate.textContent ?? '').replace(/[\uE000-\uF8FF]/g, '').replace(/\s+/g, ' ').trim()

            if (text) {
              blocks.push(`> ${text}`)
            }

            continue
          }

          const text = (candidate.textContent ?? '').replace(/[\uE000-\uF8FF]/g, '').replace(/\s+/g, ' ').trim()

          if (!text) {
            continue
          }

          if (/^H[1-6]$/.test(tag)) {
            const level = Number(tag.slice(1))
            blocks.push(`${'#'.repeat(level)} ${text}`)
            continue
          }

          blocks.push(text)
        }

        return blocks.join('\n\n')
      })
    )

    if (markdown) {
      return markdown
    }
  }

  return ''
}

async function crawlPixiUI(): Promise<void> {
  const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage()

  try {
    await mkdir(OUTPUT_DIR, { recursive: true })
    await page.goto(BASE_URL, { waitUntil: 'domcontentloaded' })
    await waitForDocPage(page)

    const items = await collectDocLinks(page)

    if (items.length === 0) {
      throw new Error('No Pixi UI documentation links were found.')
    }

    for (const item of items) {
      console.log(`Crawling ${item.text}: ${item.url}`)

      await page.goto(item.url, { waitUntil: 'domcontentloaded' })
      await waitForDocPage(page)

      const content = await extractMarkdown(page)

      if (!content) {
        console.warn(`Skipping empty page: ${item.url}`)
        continue
      }

      const markdown = createDocumentMarkdown(item.text, item.url, content)
      const fileName = `${toSlug(item.text) || 'page'}.md`
      await writeFile(new URL(fileName, OUTPUT_DIR), `${markdown}\n`, 'utf8')
    }
  } finally {
    await browser.close()
  }
}

void crawlPixiUI().catch((error) => {
  console.error(error)
  process.exitCode = 1
})